const obj = [
  {
    en: '`',
    ru: 'ё',
    className: 'btn btn_small Backquote',
    alter: '~',
  },
  {
    en: '1',
    ru: '1',
    className: 'btn btn_small Digit1',
    alter: '!',
  },
  {
    en: '2',
    ru: '2',
    className: 'btn btn_small Digit2',
    alter: '@',
  },
  {
    en: '3',
    ru: '3',
    className: 'btn btn_small Digit3',
    alter: '#',
  },
  {
    en: '4',
    ru: '4',
    className: 'btn btn_small Digit4',
    alter: '$',
  },
  {
    en: '5',
    ru: '5',
    className: 'btn btn_small Digit5',
    alter: '%',
  },
  {
    en: '6',
    ru: '6',
    className: 'btn btn_small Digit6',
    alter: '^',
  },
  {
    en: '7',
    ru: '7',
    className: 'btn btn_small Digit7',
    alter: '&',
  },
  {
    en: '8',
    ru: '8',
    className: 'btn btn_small Digit8',
    alter: '*',
  },
  {
    en: '9',
    ru: '9',
    className: 'btn btn_small Digit9',
    alter: '(',
  },
  {
    en: '0',
    ru: '0',
    className: 'btn btn_small Digit0',
    alter: ')',
  },
  {
    en: '-',
    ru: '-',
    className: 'btn btn_small Minus',
    alter: '_',
  },
  {
    en: '=',
    ru: '=',
    className: 'btn btn_small Equal',
    alter: '+',
  },
  {
    en: 'Backspace',
    ru: 'Backspace',
    className: 'btn btn_big Backspace',
  },
  {
    en: 'Tab',
    ru: 'Tab',
    className: 'btn btn_medium Tab',
  },
  {
    en: 'q',
    ru: 'й',
    className: 'btn btn_small KeyQ',
  },
  {
    en: 'w',
    ru: 'ц',
    className: 'btn btn_small KeyW',
  },
  {
    en: 'e',
    ru: 'у',
    className: 'btn btn_small KeyE',
  },
  {
    en: 'r',
    ru: 'к',
    className: 'btn btn_small KeyR',
  },
  {
    en: 't',
    ru: 'е',
    className: 'btn btn_small KeyT',
  },
  {
    en: 'y',
    ru: 'н',
    className: 'btn btn_small KeyY',
  },
  {
    en: 'u',
    ru: 'г',
    className: 'btn btn_small KeyU',
  },
  {
    en: 'i',
    ru: 'ш',
    className: 'btn btn_small KeyI',
  },
  {
    en: 'o',
    ru: 'щ',
    className: 'btn btn_small KeyO',
  },
  {
    en: 'p',
    ru: 'з',
    className: 'btn btn_small KeyP',
  },
  {
    en: '[',
    ru: 'х',
    className: 'btn btn_small BracketLeft',
    alter: '{',
  },
  {
    en: ']',
    ru: 'ъ',
    className: 'btn btn_small BracketRight',
    alter: '}',
  },
  {
    en: '\\',
    ru: '\\',
    className: 'btn btn_small Backslash',
    alter: '|',
  },
  {
    en: 'Del',
    ru: 'Del',
    className: 'btn btn_medium Delete',
  },
  {
    en: 'Caps Lock',
    ru: 'Caps Lock',
    className: 'btn btn_big CapsLock',
  },
  {
    en: 'a',
    ru: 'ф',
    className: 'btn btn_small KeyA',
  },
  {
    en: 's',
    ru: 'ы',
    className: 'btn btn_small KeyS',
  },
  {
    en: 'd',
    ru: 'в',
    className: 'btn btn_small KeyD',
  },
  {
    en: 'f',
    ru: 'а',
    className: 'btn btn_small KeyF',
  },
  {
    en: 'g',
    ru: 'п',
    className: 'btn btn_small KeyG',
  },
  {
    en: 'h',
    ru: 'р',
    className: 'btn btn_small KeyH',
  },
  {
    en: 'j',
    ru: 'о',
    className: 'btn btn_small KeyJ',
  },
  {
    en: 'k',
    ru: 'л',
    className: 'btn btn_small KeyK',
  },
  {
    en: 'l',
    ru: 'д',
    className: 'btn btn_small KeyL',
  },
  {
    en: ';',
    ru: 'ж',
    className: 'btn btn_small Semicolon',
    alter: ':',
  },
  {
    en: "'",
    ru: 'э',
    className: 'btn btn_small Quote',
    alter: '"',
  },
  {
    en: 'Enter',
    ru: 'Enter',
    className: 'btn btn_big Enter',
  },
  {
    en: 'Shift',
    ru: 'Shift',
    className: 'btn btn_big ShiftLeft',
  },
  {
    en: 'z',
    ru: 'я',
    className: 'btn btn_small KeyZ',
  },
  {
    en: 'x',
    ru: 'ч',
    className: 'btn btn_small KeyX',
  },
  {
    en: 'c',
    ru: 'с',
    className: 'btn btn_small KeyC',
  },
  {
    en: 'v',
    ru: 'м',
    className: 'btn btn_small KeyV',
  },
  {
    en: 'b',
    ru: 'и',
    className: 'btn btn_small KeyB',
  },
  {
    en: 'n',
    ru: 'т',
    className: 'btn btn_small KeyN',
  },
  {
    en: 'm',
    ru: 'ь',
    className: 'btn btn_small KeyM',
  },
  {
    en: ',',
    ru: 'б',
    className: 'btn btn_small Comma',
    alter: '<',
  },
  {
    en: '.',
    ru: 'ю',
    className: 'btn btn_small Period',
    alter: '>',
  },
  {
    en: '/',
    ru: '.',
    className: 'btn btn_small Slash',
    alter: '?',
  },
  {
    en: '\u25B2',
    ru: '\u25B2',
    className: 'btn btn_small ArrowUp',
  },
  {
    en: 'Shift',
    ru: 'Shift',
    className: 'btn btn_big ShiftRight',
  },
  {
    en: 'Ctrl',
    ru: 'Ctrl',
    className: 'btn btn_medium ControlLeft',
  },
  {
    en: 'Win',
    ru: 'Win',
    className: 'btn btn_small MetaLeft',
  },
  {
    en: 'Alt',
    ru: 'Alt',
    className: 'btn btn_small AltLeft',
  },
  {
    en: '',
    ru: '',
    className: 'btn btn_space Space',
  },
  {
    en: 'Alt',
    ru: 'Alt',
    className: 'btn btn_small AltRight',
  },
  {
    en: '\u25C0',
    ru: '\u25C0',
    className: 'btn btn_small ArrowLeft',
  },
  {
    en: '\u25BC',
    ru: '\u25BC',
    className: 'btn btn_small ArrowDown',
  },
  {
    en: '\u25B6',
    ru: '\u25B6',
    className: 'btn btn_small ArrowRight',
  },
  {
    en: 'Ctrl',
    ru: 'Ctrl',
    className: 'btn btn_medium ControlRight',
  },
];
export default obj;
